# fly.toml app configuration file generated for xiv-raid-hub on 2023-11-12T22:26:08-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xiv-raid-hub"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
